### PR TITLE
Improve Travis CI

### PR DESCRIPTION
**Pull request by webknjaz**
Helper script and linters separation.

### CODE REVIEW

**Comment by webknjaz** [comment]
(squashed a few commits)

**Comment by hugovk** [comment]
Did this 3.2/remote install anything?

https://travis-ci.org/hugovk/get-pip/jobs/368209049

**Comment by webknjaz** [comment]
Obviously not. But it is being invoked as expected. We can try removing pip first.

**Comment by webknjaz** [comment]
@hugovk added removing pip and showing pip version after install

**Comment by hugovk** [comment]
Looking good! Ready?

**Comment by webknjaz** [comment]
ready! :checkered_flag:

**Pull request merged**
